project:
  type: website

website:
  title: ""
  search: false
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: LSA-vignette.Rmd
        text: Breeding results
      - href: rna-seq-results.qmd
        text: RNA-seq results 

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



